theme: minima
title: Diving Into Data for Energy and Power
author: Matthew G. Sullivan
description: I am an old info-tech dog learning new tricks for data science and analysis. My blog explores electrical production systems from the perspective of publicly available data. Hopefully we'll all learn something and understand more about how we can live and thrive sustainably.  
